# Generated by Django 6.0.5 on 2026-06-04 22:44

from django.db import migrations


def migrate_roles(apps, schema_editor):
    Organization = apps.get_model('accounts', 'Organization')
    Permission = apps.get_model('accounts', 'Permission')
    Role = apps.get_model('accounts', 'Role')
    OrgMember = apps.get_model('accounts', 'OrgMember')
    User = apps.get_model('accounts', 'User')

    # 1. Create default Organization
    default_org, _ = Organization.objects.get_or_create(
        slug='default-academy',
        defaults={'name': 'Default Academy'}
    )

    # 2. Define default permissions
    permissions_data = [
        ('can_view_dashboard', 'Can view dashboard', 'Access basic dashboard views'),
        ('can_attend_class', 'Can attend class', 'Participate in live sessions'),
        ('can_teach_class', 'Can teach class', 'Host live sessions and teach courses'),
        ('can_manage_members', 'Can manage members', 'Add, remove, or edit students and teachers'),
        ('can_view_financials', 'Can view financials', 'View tuition payments and basic expense stats'),
        ('can_manage_financials', 'Can manage financials', 'Record payments, create invoices, and log expenses'),
        ('can_control_recordings', 'Can control recordings', 'Start, stop, pause, or resume in-call recordings'),
    ]

    permissions_map = {}
    for codename, name, desc in permissions_data:
        perm, _ = Permission.objects.get_or_create(
            codename=codename,
            defaults={'name': name, 'description': desc}
        )
        permissions_map[codename] = perm

    # 3. Define and create default roles
    roles_data = {
        'admin': {
            'name': 'Admin',
            'desc': 'Academy administrator with full access to settings, members, and financials',
            'perms': ['can_view_dashboard', 'can_manage_members', 'can_view_financials', 'can_manage_financials', 'can_control_recordings']
        },
        'teacher': {
            'name': 'Teacher',
            'desc': 'Educator who hosts live classes and teaches courses',
            'perms': ['can_view_dashboard', 'can_teach_class', 'can_control_recordings']
        },
        'student': {
            'name': 'Student',
            'desc': 'Learner who enrolls in courses and attends live classes',
            'perms': ['can_view_dashboard', 'can_attend_class']
        }
    }

    roles_map = {}
    for role_key, r_info in roles_data.items():
        role, _ = Role.objects.get_or_create(
            name=r_info['name'],
            defaults={'description': r_info['desc']}
        )
        # Assign permissions to the role
        perms_to_add = [permissions_map[p] for p in r_info['perms'] if p in permissions_map]
        role.permissions.set(perms_to_add)
        roles_map[role_key] = role

    # 4. Migrate existing users based on legacy User.role
    for user in User.objects.all():
        legacy_role = getattr(user, 'role', 'student')
        if legacy_role not in roles_map:
            legacy_role = 'student'

        assigned_role = roles_map[legacy_role]

        OrgMember.objects.get_or_create(
            organization=default_org,
            user=user,
            defaults={'role': assigned_role}
        )


def rollback_migration(apps, schema_editor):
    Organization = apps.get_model('accounts', 'Organization')
    Permission = apps.get_model('accounts', 'Permission')
    Role = apps.get_model('accounts', 'Role')
    OrgMember = apps.get_model('accounts', 'OrgMember')

    OrgMember.objects.all().delete()
    Role.objects.all().delete()
    Permission.objects.all().delete()
    Organization.objects.filter(slug='default-academy').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_course_organization_permission_academyclass_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_roles, rollback_migration),
    ]

