# Generated by Django 6.0.5 on 2026-06-08 16:23

from django.db import migrations


def migrate_data(apps, schema_editor):
    Organization = apps.get_model('accounts', 'Organization')
    OrgMember = apps.get_model('accounts', 'OrgMember')
    TuitionInvoice = apps.get_model('accounts', 'TuitionInvoice')

    # 1. Backfill OrgMember.contract_type to 'full_time'
    OrgMember.objects.all().update(contract_type='full_time')

    # 2. Backfill Organization.owner
    for org in Organization.objects.all():
        # Find first admin member
        admin_member = OrgMember.objects.filter(organization=org, role__name='Admin').first()
        if admin_member:
            org.owner = admin_member.user
            org.save()
        else:
            # Fallback to any member
            any_member = OrgMember.objects.filter(organization=org).first()
            if any_member:
                org.owner = any_member.user
                org.save()
            else:
                # Log or set to None
                print(f"Organization '{org.name}' has no members, owner left as NULL.")

    # 3. Backfill TuitionInvoice.invoice_number sequential per organization
    for org in Organization.objects.all():
        invoices = TuitionInvoice.objects.filter(organization=org).order_by('created_at', 'id')
        for idx, invoice in enumerate(invoices, start=1):
            invoice.invoice_number = f"INV-{org.id}-{idx:04d}"
            invoice.save()


def rollback_data(apps, schema_editor):
    Organization = apps.get_model('accounts', 'Organization')
    TuitionInvoice = apps.get_model('accounts', 'TuitionInvoice')

    # Clear owner
    Organization.objects.all().update(owner=None)

    # Clear invoice numbers
    TuitionInvoice.objects.all().update(invoice_number="")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_accounts_au_organiz_27ec26_idx_accounts_au_organiz_8ee750_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_data, rollback_data),
    ]

