# Generated by Django 6.0.5 on 2026-06-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_organization_owner'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tuitioninvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number', ''), _negated=True), fields=('organization', 'invoice_number'), name='unique_invoice_number_per_org'),
        ),
    ]
