# Generated by Django 6.0.5 on 2026-06-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_tuitioninvoice_unique_invoice_number_per_org'),
        ('rooms', '0005_room_recording_grants'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='academyclass',
            index=models.Index(fields=['course', 'is_active'], name='accounts_ac_course__55376b_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['organization', 'is_active'], name='accounts_co_organiz_352368_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['academy_class', 'is_active'], name='accounts_en_academy_ad98c2_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'is_active'], name='accounts_en_student_d660d2_idx'),
        ),
    ]
