# Generated by Django 6.0.5 on 2026-06-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_academyclass_accounts_ac_course__55376b_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expenseitem',
            index=models.Index(fields=['organization', 'category'], name='accounts_ex_organiz_ddecf6_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseitem',
            index=models.Index(fields=['organization', '-incurred_at'], name='accounts_ex_organiz_9ba06b_idx'),
        ),
        migrations.AddIndex(
            model_name='tuitioninvoice',
            index=models.Index(fields=['organization', 'student'], name='accounts_tu_organiz_f4fbbc_idx'),
        ),
        migrations.AddIndex(
            model_name='tuitioninvoice',
            index=models.Index(fields=['organization', 'status'], name='accounts_tu_organiz_e3e82c_idx'),
        ),
    ]
