# Generated by Django 6.0.5 on 2026-06-08 22:48

from django.db import migrations

def migrate_class_to_session(apps, schema_editor):
    AcademyClass = apps.get_model('accounts', 'AcademyClass')
    Course = apps.get_model('accounts', 'Course')
    Session = apps.get_model('accounts', 'Session')
    Room = apps.get_model('rooms', 'Room')
    Recording = apps.get_model('rooms', 'Recording')

    # Find all AcademyClasses that have a room
    for academy_class in AcademyClass.objects.filter(room__isnull=False):
        try:
            room = Room.objects.get(pk=academy_class.room_id)
        except Room.DoesNotExist:
            continue

        try:
            course = Course.objects.get(pk=academy_class.course_id)
            org_id = course.organization_id
        except Course.DoesNotExist:
            org_id = None

        # Create Session for the AcademyClass + Room
        session = Session.objects.create(
            academy_class=academy_class,
            organization_id=org_id,
            host_id=room.host_id,
            created_by_id=None,
            title=f"{academy_class.name} (Migrated)",
            status='completed',
            scheduled_start=room.started_at or room.created_at,
            scheduled_end=room.ended_at
        )

        # Update Room fields
        room.session = session
        room.organization_id = org_id
        room.meeting_type = 'class_session'
        room.save()

        # Update Recordings linked to this Room
        Recording.objects.filter(room=room).update(session=session)

def rollback_class_to_session(apps, schema_editor):
    Session = apps.get_model('accounts', 'Session')
    Room = apps.get_model('rooms', 'Room')
    Recording = apps.get_model('rooms', 'Recording')

    # Reset Room and Recording fields
    Room.objects.filter(meeting_type='class_session').update(
        session=None,
        organization=None,
        meeting_type='ad_hoc'
    )
    Recording.objects.filter(session__isnull=False).update(session=None)
    
    # Delete the created Session objects
    Session.objects.filter(title__endswith=" (Migrated)").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_session_attendance'),
        ('rooms', '0006_recording_session_room_meeting_type_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_class_to_session, rollback_class_to_session),
    ]
