# Generated by Django 6.0.5 on 2026-06-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_create_session_attendance'),
        ('rooms', '0005_room_recording_grants'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'live')), fields=('academy_class', 'status'), name='unique_live_session_per_class'),
        ),
    ]
