# Generated by Django 6.0.5 on 2026-06-09 00:00

import django.db.models.deletion
from django.db import migrations


def migrate_class_to_session(apps, schema_editor):
    AcademyClass = apps.get_model('accounts', 'AcademyClass')
    Session = apps.get_model('accounts', 'Session')
    Room = apps.get_model('rooms', 'Room')
    Recording = apps.get_model('rooms', 'Recording')

    # Find classes that have room_id set (exclude null)
    classes = AcademyClass.objects.exclude(room_id__isnull=True)
    
    for ac in classes:
        # Check if a session already exists for this class to ensure idempotency
        if Session.objects.filter(academy_class=ac).exists():
            continue

        try:
            room = Room.objects.get(id=ac.room_id)
        except Room.DoesNotExist:
            continue
            
        # Determine organization
        org = ac.course.organization
        
        # Create a session
        session = Session.objects.create(
            academy_class=ac,
            organization=org,
            host=room.host,
            created_by=None,
            active_room=room,
            title=f"{ac.name} (Migrated)",
            status='completed',
            scheduled_start=room.started_at or room.created_at,
            scheduled_end=room.ended_at
        )
        
        # Link Room to Session
        room.session = session
        room.organization = org
        room.meeting_type = 'class_session'
        room.save(update_fields=['session', 'organization', 'meeting_type'])
        
        # Link Recordings of this Room to the new Session
        Recording.objects.filter(room=room).update(session=session)


def rollback_class_to_session(apps, schema_editor):
    Session = apps.get_model('accounts', 'Session')
    Room = apps.get_model('rooms', 'Room')
    Recording = apps.get_model('rooms', 'Recording')
    
    # Nullify links in Room and Recording
    Room.objects.filter(meeting_type='class_session').update(session=None, organization=None, meeting_type='ad_hoc')
    Recording.objects.exclude(session__isnull=True).update(session=None)
    
    # Delete migrated sessions
    Session.objects.exclude(academy_class__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_session_unique_live_session_per_class'),
        ('rooms', '0006_recording_session_room_meeting_type_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_class_to_session, rollback_class_to_session),
    ]
