# Generated by Django 6.0.5 on 2026-06-08 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_migrate_class_to_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academyclass',
            name='room',
        ),
    ]
