# Generated by Django 6.0.5 on 2026-06-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_certificate'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'created_at'], name='accounts_au_organiz_b99df7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'action', 'created_at'], name='accounts_au_organiz_77f1c6_idx'),
        ),
    ]
