# Generated by Django 6.0.5 on 2026-06-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auditlog_accounts_au_organiz_b99df7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitioninvoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
    ]
