# Generated by Django 6.0.5 on 2026-06-15 16:42

import django.db.models.deletion
from django.db import migrations, models


def migrate_json_items_to_table(apps, schema_editor):
    import json
    TuitionInvoice = apps.get_model('accounts', 'TuitionInvoice')
    InvoiceLineItem = apps.get_model('accounts', 'InvoiceLineItem')
    
    for invoice in TuitionInvoice.objects.all():
        notes_val = invoice.notes or ""
        if notes_val.strip().startswith("{") and notes_val.strip().endswith("}"):
            try:
                data = json.loads(notes_val)
                plain_notes = data.get("notes", "")
                items_list = data.get("items", [])
                
                invoice.notes = plain_notes
                invoice.save()
                
                for item in items_list:
                    InvoiceLineItem.objects.create(
                        invoice=invoice,
                        description=item.get("description", "Tuition Item"),
                        quantity=int(item.get("quantity", 1)),
                        unit_price=float(item.get("unit_price", 0))
                    )
            except Exception:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='accounts.tuitioninvoice')),
            ],
        ),
        migrations.RunPython(migrate_json_items_to_table, reverse_code=migrations.RunPython.noop, elidable=True),
    ]

