# Generated by Django 6.0.5 on 2026-06-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_invoicelineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='suspension_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
