# Generated by Django 6.0.5 on 2026-06-16 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_create_mentor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='academyclass',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
