# Generated by Django 6.0.5 on 2026-06-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='approval_required_to_join',
            field=models.BooleanField(default=False),
        ),
    ]
