# Generated by Django 6.0.5 on 2026-06-19 04:35

from django.db import migrations, models


def generate_invite_codes(apps, schema_editor):
    import random
    import string
    Organization = apps.get_model('accounts', 'Organization')
    chars = string.ascii_uppercase + string.digits
    for org in Organization.objects.all():
        if not org.invite_code:
            code = None
            while not code:
                temp_code = ''.join(random.choice(chars) for _ in range(6))
                if not Organization.objects.filter(invite_code=temp_code).exists():
                    code = temp_code
            org.invite_code = code
            org.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_organization_approval_required_to_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='invite_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.RunPython(generate_invite_codes, reverse_code=migrations.RunPython.noop),
    ]
