# Generated by Django 6.0.5 on 2026-06-19 11:58

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_organization_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='org_logos/', validators=[accounts.models.validate_org_logo]),
        ),
    ]
