# Generated by Django 6.0.5 on 2026-07-13 15:53

import accounts.models
from django.db import migrations, models


def migrate_existing_capacities(apps, schema_editor):
    AcademyClass = apps.get_model('accounts', 'AcademyClass')
    AcademyClass.objects.exclude(max_students=None).update(capacity_mode='limited')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='academyclass',
            name='capacity_mode',
            field=models.CharField(choices=[('unlimited', 'Unlimited'), ('limited', 'Limited')], default='unlimited', max_length=20),
        ),
        migrations.AddField(
            model_name='academyclass',
            name='scheduling_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/', validators=[accounts.models.validate_no_svg]),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='expense_attachments/', validators=[accounts.models.validate_no_svg]),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[accounts.models.validate_no_svg]),
        ),
        migrations.RunPython(migrate_existing_capacities, reverse_code=migrations.RunPython.noop),
    ]
