# Generated by Django 6.0.5 on 2026-07-13 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_academyclass_capacity_mode_and_more'),
        ('rooms', '0006_recording_session_room_meeting_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_id', models.CharField(max_length=100, unique=True)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_session_student_attendance',
        ),
        migrations.AddField(
            model_name='academyclass',
            name='google_calendar_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='academyclass',
            name='recurrence_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academyclass',
            name='recurrence_end_mode',
            field=models.CharField(choices=[('date', 'End Date'), ('occurrences', 'Number of Occurrences')], default='date', max_length=20),
        ),
        migrations.AddField(
            model_name='academyclass',
            name='recurrence_max_occurrences',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academyclass',
            name='recurrence_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academyclass',
            name='recurrence_timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
        migrations.AddField(
            model_name='academyclass',
            name='recurrence_weekdays',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.session'),
        ),
        migrations.AddField(
            model_name='classoccurrence',
            name='academy_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='accounts.academyclass'),
        ),
        migrations.AddField(
            model_name='classoccurrence',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='occurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.classoccurrence'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('session__isnull', False)), fields=('session', 'student'), name='unique_session_student_attendance'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('occurrence__isnull', False)), fields=('occurrence', 'student'), name='unique_occurrence_student_attendance'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('session__isnull', False), ('occurrence__isnull', True)), models.Q(('session__isnull', True), ('occurrence__isnull', False)), _connector='OR'), name='attendance_target_xor'),
        ),
        migrations.AddIndex(
            model_name='classoccurrence',
            index=models.Index(fields=['academy_class', 'status'], name='accounts_cl_academy_b6af93_idx'),
        ),
        migrations.AddIndex(
            model_name='classoccurrence',
            index=models.Index(fields=['scheduled_start'], name='accounts_cl_schedul_a7a840_idx'),
        ),
    ]
