# Generated by Django 6.0.5 on 2026-08-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_classoccurrence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='branding',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
