# Generated by Django 6.0.5 on 2026-05-28 18:02

import django.db.models.deletion
import rooms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.CharField(default=rooms.models._make_recording_token, editable=False, max_length=32, unique=True)),
                ('quality', models.CharField(choices=[('720p', '720p'), ('1080p', '1080p')], default='720p', max_length=10)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('recording', 'Recording'), ('paused', 'Paused'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='starting', max_length=20)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('trim_start_seconds', models.FloatField(default=0)),
                ('trim_end_seconds', models.FloatField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(help_text='Host who started this recording.', on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='rooms.room')),
                ('visible_to', models.ManyToManyField(blank=True, help_text='Participants the host shared the published recording with.', related_name='visible_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordingSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('egress_id', models.CharField(db_index=True, max_length=128)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('duration_seconds', models.FloatField(default=0)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='rooms.recording')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['room', '-started_at'], name='rooms_recor_room_id_8392ff_idx'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['owner', '-started_at'], name='rooms_recor_owner_i_ea6a27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recordingsegment',
            unique_together={('recording', 'index')},
        ),
    ]
