# Generated by Django 6.0.5 on 2026-05-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_recording_recordingsegment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='is_link_shared',
            field=models.BooleanField(default=False),
        ),
    ]
