# Generated by Django 6.0.5 on 2026-05-30 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_recordingview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='recording_grants',
            field=models.ManyToManyField(blank=True, help_text='Non-host participants the host has authorized to control recording in this specific room.', related_name='rooms_with_recording_grant', to=settings.AUTH_USER_MODEL),
        ),
    ]
