# Generated by Django 6.0.5 on 2026-06-08 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_session_unique_live_session_per_class'),
        ('rooms', '0005_room_recording_grants'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='accounts.session'),
        ),
        migrations.AddField(
            model_name='room',
            name='meeting_type',
            field=models.CharField(choices=[('class_session', 'Class Session'), ('ad_hoc', 'Ad-hoc')], default='ad_hoc', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='room',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='accounts.session'),
        ),
    ]
