# Generated by Django 6.0.5 on 2026-07-13 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_classoccurrence_and_more'),
        ('rooms', '0006_recording_session_room_meeting_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='occurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='accounts.classoccurrence'),
        ),
        migrations.AddField(
            model_name='room',
            name='occurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='accounts.classoccurrence'),
        ),
    ]
