# Generated by Django 6.0.5 on 2026-08-15 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_recording_occurrence_room_occurrence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomparticipant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='guest_identity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roomparticipant',
            name='role',
            field=models.CharField(choices=[('host', 'Host'), ('participant', 'Participant'), ('guest', 'Guest')], default='participant', max_length=20),
        ),
        migrations.AlterField(
            model_name='roomparticipant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='roomparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('room', 'user'), name='unique_authenticated_user_per_room'),
        ),
    ]
