# Generated by Django 6.0.5 on 2026-08-18 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_roomparticipant_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Completely block new participants from joining.'),
        ),
        migrations.AddField(
            model_name='room',
            name='require_approval',
            field=models.BooleanField(default=False, help_text='Joining via invite link requires host approval.'),
        ),
        migrations.CreateModel(
            name='LobbyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_identity', models.CharField(blank=True, max_length=100, null=True)),
                ('guest_name', models.CharField(blank=True, max_length=100, null=True)),
                ('display_name', models.CharField(max_length=150)),
                ('is_guest', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('admitted', 'Admitted'), ('denied', 'Denied'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('livekit_token', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_requests', to='rooms.room')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobby_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['room', 'status'], name='rooms_lobby_room_id_fced92_idx')],
            },
        ),
    ]
