# Generated by Django 6.0.5 on 2026-08-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_lobby_and_access_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='duration_limit_minutes',
            field=models.PositiveIntegerField(blank=True, default=60, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_duration_limited',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='warning_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_participants',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
