# Generated by Django 6.0.5 on 2026-08-23 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_room_duration_limit_minutes_room_is_duration_limited_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='co_hosts',
            field=models.ManyToManyField(blank=True, help_text='Participants authorized as Co-Hosts with room moderator privileges.', related_name='co_hosted_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roomparticipant',
            name='role',
            field=models.CharField(choices=[('host', 'Host'), ('co_host', 'Co-Host'), ('participant', 'Participant'), ('guest', 'Guest')], default='participant', max_length=20),
        ),
    ]
