# Generated by Django 6.0.5 on 2026-08-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_room_co_hosts_alter_roomparticipant_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='lock_camera',
            field=models.BooleanField(default=False, help_text='Lock cameras for regular participants unless permission is granted.'),
        ),
        migrations.AddField(
            model_name='room',
            name='lock_microphone',
            field=models.BooleanField(default=False, help_text='Lock microphones for regular participants unless permission is granted.'),
        ),
        migrations.AddField(
            model_name='room',
            name='lock_screen_share',
            field=models.BooleanField(default=False, help_text='Lock screen sharing for regular participants unless permission is granted.'),
        ),
        migrations.AddField(
            model_name='room',
            name='mute_cam_on_join',
            field=models.BooleanField(default=False, help_text='Turn off participant cameras by default upon entry.'),
        ),
        migrations.AddField(
            model_name='room',
            name='mute_mic_on_join',
            field=models.BooleanField(default=False, help_text='Mute participant microphones by default upon entry.'),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='can_share_screen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='can_use_camera',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='can_use_microphone',
            field=models.BooleanField(default=True),
        ),
    ]
