# Generated by Django 6.0.5 on 2026-08-23 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_room_lock_camera_room_lock_microphone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='lock_document_presentation',
            field=models.BooleanField(default=True, help_text='Lock document upload and presentation for regular members unless host unlocks or grants individually.'),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='can_upload_presentation',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PresentationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_uploader_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='room_presentations/%Y/%m/')),
                ('title', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Document'), ('image', 'Image'), ('slide', 'Presentation Slide'), ('other', 'Other Document')], default='pdf', max_length=20)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('total_pages', models.PositiveIntegerField(default=1)),
                ('current_page', models.PositiveIntegerField(default=1)),
                ('is_active_on_stage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='rooms.room')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
