# Generated by Django 6.0.5 on 2026-08-27

import rooms.models
import rooms.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_room_lock_document_presentation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationdocument',
            name='file',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=rooms.models.presentation_output_upload_path,
            ),
        ),
        migrations.AddField(
            model_name='presentationdocument',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='presentationdocument',
            name='processing_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentationdocument',
            name='processing_error_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='presentationdocument',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentationdocument',
            name='processing_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('processing', 'Processing'),
                    ('ready', 'Ready'),
                    ('failed', 'Failed'),
                ],
                default='ready',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='presentationdocument',
            name='source_file',
            field=models.FileField(
                blank=True,
                null=True,
                storage=rooms.storage.PrivatePresentationStorage(),
                upload_to=rooms.models.presentation_source_upload_path,
            ),
        ),
        migrations.AddField(
            model_name='presentationdocument',
            name='source_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('pdf', 'PDF'),
                    ('png', 'PNG'),
                    ('jpeg', 'JPEG'),
                    ('webp', 'WebP'),
                    ('ppt', 'PowerPoint'),
                    ('pptx', 'PowerPoint Open XML'),
                    ('odp', 'OpenDocument Presentation'),
                    ('doc', 'Word Document'),
                    ('docx', 'Word Open XML'),
                ],
                default='',
                max_length=10,
            ),
        ),
    ]
