# Generated by Django 6.0.5 on 2026-06-16 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0023_organization_is_suspended_organization_suspended_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('max_students', models.IntegerField(default=100)),
                ('max_teachers', models.IntegerField(default=10)),
                ('max_courses', models.IntegerField(default=10)),
                ('max_storage_gb', models.DecimalField(decimal_places=2, default=5.0, max_digits=8)),
                ('max_recording_minutes', models.IntegerField(default=120)),
                ('max_active_sessions', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_events', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='BillingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('stripe_invoice_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('invoice_pdf_url', models.URLField(blank=True, max_length=1024)),
                ('issued_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_invoices', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('unpaid', 'Unpaid'), ('downgraded', 'Downgraded'), ('read_only', 'Read Only'), ('canceled', 'Canceled')], db_index=True, default='trialing', max_length=50)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('payment_failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.subscriptionplan')),
            ],
        ),
    ]
