# Generated by Django 6.0.5 on 2026-08-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_group_duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_meeting_participants',
            field=models.IntegerField(default=25),
        ),
    ]
