export const Strings = {
  app: {
    name: "EduSpace",
    tagline: "Your educational platform",
  },
  auth: {
    signIn: "Sign In",
    signUp: "Create Account",
    signOut: "Sign Out",
    username: "Username",
    password: "Password",
    confirmPassword: "Confirm Password",
    fullName: "Full Name",
    email: "Email",
    iAmA: "I am a",
    student: "Student",
    teacher: "Teacher",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    createOne: "Create one",
    signingIn: "Signing in...",
    placeholders: {
      username: "Enter your username",
      password: "Enter your password",
      confirmPassword: "Repeat your password",
      fullName: "Your full name",
      email: "you@example.com",
    },
    hints: {
      username: "Letters, numbers and underscores only",
      password: "Min 8 characters",
    },
    errors: {
      loginFailed: "Login failed",
      registerFailed: "Registration failed",
    },
  },
  room: {
    leave: "Leave",
    leaveSession: "Leave session",
    mic: "Mic",
    camera: "Camera",
    share: "Share",
    people: "People",
    chat: "Chat",
    tools: "Tools",
    settings: "Settings",
    participants: "Participants",
    host: "Host",
    students: "Students",
    mute: "Mute",
    unmute: "Unmute",
    turnOffCamera: "Turn off camera",
    turnOnCamera: "Turn on camera",
    shareScreen: "Share your screen",
    sendMessage: "Send a message...",
    tooltips: {
      mic: "Mute / Unmute · Ctrl+D",
      camera: "Turn camera on/off · Ctrl+E",
      screenShare: "Share your screen",
      participants: "Participants",
      chat: "Chat",
      tools: "Session tools",
      settings: "Audio & video settings",
      leave: "Leave session",
    },
  },
  dashboard: {
    title: "Dashboard",
    welcome: "Welcome back",
    startCall: "Start Call",
    launchGame: "Launch Game",
    newExam: "New Exam",
    recordings: "Recordings",
    sessionsThisWeek: "Sessions this week",
    activeStudents: "Active students",
    avgAttendance: "Avg attendance",
    recentSessions: "Recent Sessions",
    seeAll: "See all →",
    noSessions: "No sessions yet",
    startFirst: "Start your first session",
  },
  common: {
    loading: "Loading...",
    error: "Something went wrong",
    retry: "Try again",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    delete: "Delete",
    close: "Close",
    back: "Back",
    next: "Next",
    done: "Done",
    soon: "Soon",
    live: "● Live",
    copied: "Copied!",
  },
  tools: {
    launchGame: "Launch Game",
    launchGameDesc: "Add game to session",
    whiteboard: "Whiteboard",
    whiteboardDesc: "Collaborative drawing",
    quickExam: "Quick Exam",
    quickExamDesc: "Start exam in session",
    aiSummary: "AI Summary",
    aiSummaryDesc: "Auto-summarize session",
    fileShare: "File Share",
    fileShareDesc: "Share presentations",
  },
} as const;
