# Generated by Django 6.0.5 on 2026-06-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_in_call_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('word_guess', 'Word Guess'), ('word_guess_classroom', 'Word Guess (Classroom)'), ('grammar', 'Grammar'), ('vocab', 'Vocabulary')], max_length=50),
        ),
    ]
