# Generated by Django 6.0.5 on 2026-06-14 15:57

import django.db.models.deletion
from django.db import migrations, models

def backfill_game_sessions(apps, schema_editor):
    GameSession = apps.get_model('games', 'GameSession')
    GameParticipant = apps.get_model('games', 'GameParticipant')
    OrgMember = apps.get_model('accounts', 'OrgMember')
    Organization = apps.get_model('accounts', 'Organization')
    Room = apps.get_model('rooms', 'Room')
    User = apps.get_model('accounts', 'User')
    
    for session in GameSession.objects.filter(organization__isnull=True):
        assigned_org = None
        
        # Priority A: Direct Room Organization
        try:
            room = Room.objects.get(room_code=session.room_code)
            if room.organization_id:
                assigned_org = Organization.objects.get(pk=room.organization_id)
        except Room.DoesNotExist:
            room = None

        # Priority B: Related class/course organization
        if not assigned_org and room:
            # 1. Check room's related session organization
            if room.session_id:
                SessionModel = apps.get_model('accounts', 'Session')
                try:
                    assoc_session = SessionModel.objects.get(pk=room.session_id)
                    if assoc_session.organization_id:
                        assigned_org = Organization.objects.get(pk=assoc_session.organization_id)
                except SessionModel.DoesNotExist:
                    pass
            
            # 2. Check room's academy classes
            if not assigned_org:
                AcademyClass = apps.get_model('accounts', 'AcademyClass')
                classes = AcademyClass.objects.filter(room=room)
                org_ids = set(c.course.organization_id for c in classes if c.course and c.course.organization_id)
                if len(org_ids) == 1:
                    assigned_org = Organization.objects.get(pk=list(org_ids)[0])

        # Priority C: Participant organization consistency
        if not assigned_org:
            participants = GameParticipant.objects.filter(session=session)
            participant_user_ids = [p.user_id for p in participants]
            if participant_user_ids:
                memberships = OrgMember.objects.filter(user_id__in=participant_user_ids, is_active=True)
                org_ids = set(m.organization_id for m in memberships)
                if len(org_ids) == 1:
                    assigned_org = Organization.objects.get(pk=list(org_ids)[0])

        # Priority D: Host membership (only if exactly one active organization exists)
        if not assigned_org:
            host_memberships = OrgMember.objects.filter(user_id=session.host_id, is_active=True)
            org_ids = set(m.organization_id for m in host_memberships)
            if len(org_ids) == 1:
                assigned_org = Organization.objects.get(pk=list(org_ids)[0])

        # Resolve ambiguity
        if not assigned_org:
            try:
                host_user = User.objects.get(pk=session.host_id)
                host_str = f"{host_user.username} (ID: {session.host_id})"
            except User.DoesNotExist:
                host_str = f"ID: {session.host_id}"
                
            raise Exception(
                f"Data Migration Failure: Cannot determine organization ownership deterministically "
                f"for GameSession ID: {session.id}, Room Code: {session.room_code}, Host: {host_str}. "
                f"Please manually assign an organization or associate the session with a Room before migrating."
            )
            
        session.organization = assigned_org
        session.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_certificate'),
        ('games', '0002_game_is_in_call_only_alter_game_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='accounts.organization'),
        ),
        migrations.RunPython(backfill_game_sessions, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='gamesession',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='accounts.organization'),
        ),
    ]
