# Generated by Django 6.0.5 on 2026-06-10 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_question_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'started')), fields=('assessment', 'student'), name='unique_active_submission_per_student'),
        ),
    ]
