# Generated by Django 6.0.5 on 2026-06-19 13:28

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_assignment_assignmentsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignments/', validators=[accounts.models.validate_no_svg]),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', validators=[accounts.models.validate_no_svg]),
        ),
    ]
