# Generated by Django 6.0.5 on 2026-07-13 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_academyclass_capacity_mode_and_more'),
        ('assessments', '0005_alter_assignment_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='accounts.session'),
        ),
    ]
