# Generated by Django 6.0.5 on 2026-07-13 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_classoccurrence_and_more'),
        ('assessments', '0006_assignment_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='occurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='accounts.classoccurrence'),
        ),
    ]
