# Generated by Django 6.0.5 on 2026-08-29 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_existing_media_owners(apps, schema_editor):
    del schema_editor
    MediaAsset = apps.get_model('media_library', 'MediaAsset')
    Organization = apps.get_model('accounts', 'Organization')
    organization_owners = dict(Organization.objects.values_list('id', 'owner_id'))
    assets = list(MediaAsset.objects.filter(owner__isnull=True))
    for asset in assets:
        asset.owner_id = asset.uploader_id or organization_owners[asset.organization_id]
    MediaAsset.objects.bulk_update(assets, ['owner'])


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
        ('rooms', '0014_presentation_processing_pipeline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mediaasset',
            name='media_libra_organiz_da85cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='mediaasset',
            name='media_libra_organiz_76a0d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='sharedplaybacksession',
            name='media_libra_organiz_a06ae1_idx',
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_media_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(assign_existing_media_owners, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='mediaasset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_media_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['owner', 'is_deleted', '-created_at'], name='media_libra_owner_i_9c39b5_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['owner', 'status'], name='media_libra_owner_i_563d40_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedplaybacksession',
            index=models.Index(fields=['asset', '-started_at'], name='media_libra_asset_i_ae840e_idx'),
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='sharedplaybacksession',
            name='organization',
        ),
    ]
