# Generated by Django 6.0.5 on 2026-08-29 01:30

import django.db.models.deletion
import media_library.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_detach_from_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaUploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.CharField(default=media_library.models._make_public_token, editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('aborted', 'Aborted'), ('failed', 'Failed')], default='initiated', max_length=16)),
                ('provider_upload_id', models.CharField(max_length=500)),
                ('object_key', models.CharField(max_length=500)),
                ('expected_size_bytes', models.PositiveBigIntegerField()),
                ('uploaded_bytes', models.PositiveBigIntegerField(default=0)),
                ('part_size_bytes', models.PositiveIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='media_library.mediaasset')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['asset', 'status', '-created_at'], name='media_libra_asset_i_6d2c3f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['initiated', 'uploading'])), fields=('asset',), name='one_active_upload_per_media_asset')],
            },
        ),
    ]
