# Generated by Django 6.0.5 on 2026-08-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0003_multipart_upload_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('inspecting', 'Inspecting'), ('probing', 'Probing'), ('processing', 'Processing'), ('partially_playable', 'Partially playable'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploading', max_length=32),
        ),
    ]
