# Generated by Django 6.0.5 on 2026-08-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0004_add_media_probing_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='master_manifest_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
