# Generated by Django 6.0.5 on 2026-08-29 22:29

import django.db.models.deletion
import media_library.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0005_add_master_manifest_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressiveMediaUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.CharField(default=media_library.models._make_public_token, editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('uploading', 'Uploading'), ('verifying', 'Verifying chunks'), ('ingesting', 'Progressive ingest'), ('finalizing', 'Finalizing source'), ('completed', 'Completed'), ('fallback_required', 'Fallback required'), ('aborted', 'Aborted'), ('failed', 'Failed')], default='initiated', max_length=32)),
                ('compatibility', models.CharField(choices=[('pending', 'Pending verification'), ('eligible', 'Eligible for progressive ingest'), ('ineligible', 'Requires complete-upload fallback')], default='pending', max_length=16)),
                ('expected_size_bytes', models.PositiveBigIntegerField()),
                ('uploaded_bytes', models.PositiveBigIntegerField(default=0)),
                ('contiguous_uploaded_bytes', models.PositiveBigIntegerField(default=0)),
                ('contiguous_verified_bytes', models.PositiveBigIntegerField(default=0)),
                ('chunk_size_bytes', models.PositiveIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('object_prefix', models.CharField(max_length=500, unique=True)),
                ('fallback_code', models.CharField(blank=True, default='', max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressive_uploads', to='media_library.mediaasset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressiveMediaChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('object_key', models.CharField(max_length=500, unique=True)),
                ('expected_size_bytes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending upload'), ('uploaded', 'Uploaded'), ('verified', 'Checksum verified'), ('consumed', 'Consumed by ingest'), ('failed', 'Verification failed')], default='pending', max_length=16)),
                ('etag', models.CharField(blank=True, default='', max_length=200)),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='media_library.progressivemediaupload')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='progressivemediaupload',
            index=models.Index(fields=['asset', 'status', '-created_at'], name='media_libra_asset_i_7f3ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='progressivemediaupload',
            index=models.Index(fields=['status', 'expires_at'], name='media_libra_status_ceaf7d_idx'),
        ),
        migrations.AddConstraint(
            model_name='progressivemediaupload',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['initiated', 'uploading', 'verifying', 'ingesting', 'finalizing'])), fields=('asset',), name='one_active_progressive_upload_per_asset'),
        ),
        migrations.AddIndex(
            model_name='progressivemediachunk',
            index=models.Index(fields=['upload', 'status', 'sequence'], name='media_libra_upload__5fcd0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='progressivemediachunk',
            constraint=models.UniqueConstraint(fields=('upload', 'sequence'), name='unique_progressive_chunk_sequence'),
        ),
    ]
