# Generated by Django 6.0.5 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0006_progressivemediaupload_progressivemediachunk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressivemediaupload',
            name='ingest_attempt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progressivemediaupload',
            name='ingest_failure_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='progressivemediaupload',
            name='ingest_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressivemediaupload',
            name='ingest_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressivemediaupload',
            name='ingest_prefix',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='progressivemediaupload',
            name='ingest_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressivemediaupload',
            name='last_consumed_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveConstraint(
            model_name='progressivemediaupload',
            name='one_active_progressive_upload_per_asset',
        ),
        migrations.AddConstraint(
            model_name='progressivemediaupload',
            constraint=models.UniqueConstraint(
                condition=models.Q(status__in=[
                    'initiated', 'uploading', 'verifying', 'ingesting',
                    'finalizing', 'fallback_required',
                ]),
                fields=('asset',),
                name='one_active_progressive_upload_per_asset',
            ),
        ),
    ]
