# Generated by Django 6.0.5 on 2026-09-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0008_sharedplaybacksession_sync_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='active_task_id',
            field=models.CharField(blank=True, default='', max_length=155),
        ),
    ]
