// words.js — Jobzlingo Word Quest Database
// 59 career-themed words: 20 easy + 19 medium + 20 hard
// Schema: { word, sentence, category, hintCategory, difficulty, tip }
// hintCategory is shown in hint #1 — it is intentionally generic so it never
// contains the answer word (fixes the REMOTE → "Remote Work" reveal bug).

const WORD_DATABASE = [
  // ========== EASY ==========
  { word: "JOB",    sentence: "I just got a new ____ at a tech company downtown.",          category: "HR",          hintCategory: "Human Resources", difficulty: "easy", tip: "The average person changes jobs 12 times during their career." },
  { word: "BOSS",   sentence: "My ____ approved my vacation request this morning.",          category: "HR",          hintCategory: "Human Resources", difficulty: "easy", tip: "A good boss can make or break your work experience." },
  { word: "PAY",    sentence: "I receive my ____ on the first day of every month.",          category: "Finance",     hintCategory: "Finance",         difficulty: "easy", tip: "Always negotiate your pay — 70% of people who ask receive more." },
  { word: "WORK",   sentence: "I love my ____ because it lets me be creative every day.",    category: "HR",          hintCategory: "Human Resources", difficulty: "easy", tip: "Find work you love and you'll never work a day in your life." },
  { word: "TEAM",   sentence: "Our ____ won the company award for best collaboration.",      category: "HR",          hintCategory: "Human Resources", difficulty: "easy", tip: "Strong teams are built on trust and clear communication." },
  { word: "DESK",   sentence: "I keep my ____ organized with a calendar and laptop.",        category: "Remote Work", hintCategory: "Work Style",      difficulty: "easy", tip: "A clean desk leads to a clear mind and better focus." },
  { word: "EMAIL",  sentence: "Please send me an ____ with the meeting details.",            category: "Remote Work", hintCategory: "Work Style",      difficulty: "easy", tip: "Check email twice a day instead of constantly for better focus." },
  { word: "PHONE",  sentence: "I'll give you a quick ____ call after lunch.",                category: "Remote Work", hintCategory: "Work Style",      difficulty: "easy", tip: "Sometimes a 2-minute phone call saves a 20-email thread." },
  { word: "OFFICE", sentence: "Our new ____ has a great view of the city skyline.",          category: "Remote Work", hintCategory: "Work Style",      difficulty: "easy", tip: "The right office environment can boost productivity by 20%." },
  { word: "MONEY",  sentence: "Saving ____ each month builds long-term financial security.", category: "Finance",     hintCategory: "Finance",         difficulty: "easy", tip: "Save at least 20% of your income for future financial freedom." },
  { word: "HIRE",   sentence: "We plan to ____ five new engineers this quarter.",            category: "HR",          hintCategory: "Human Resources", difficulty: "easy", tip: "Hire for attitude, train for skills — culture fit matters most." },
  { word: "ROLE",   sentence: "She accepted a leadership ____ in the marketing department.", category: "HR",          hintCategory: "Human Resources", difficulty: "easy", tip: "Make sure your role aligns with your long-term career goals." },
  { word: "SKILL",  sentence: "Communication is the most important ____ in any career.",     category: "HR",          hintCategory: "Human Resources", difficulty: "easy", tip: "Learn one new skill every year to stay competitive." },
  { word: "GOAL",   sentence: "My main ____ this year is to get promoted to senior level.",  category: "HR",          hintCategory: "Human Resources", difficulty: "easy", tip: "Write down your goals — you're 42% more likely to achieve them." },
  { word: "TASK",   sentence: "I have one more ____ to finish before the end of the day.",   category: "HR",          hintCategory: "Human Resources", difficulty: "easy", tip: "Tackle your hardest task first thing in the morning." },
  { word: "PLAN",   sentence: "Let's make a ____ to launch the product next month.",         category: "HR",          hintCategory: "Human Resources", difficulty: "easy", tip: "A goal without a plan is just a wish — always plan your steps." },
  { word: "IDEA",   sentence: "She came up with a brilliant ____ during the brainstorm.",    category: "Marketing",   hintCategory: "Marketing",       difficulty: "easy", tip: "Keep a notebook with you — great ideas come at random moments." },
  { word: "CHAT",   sentence: "Let's have a quick ____ about your career goals.",            category: "Remote Work", hintCategory: "Work Style",      difficulty: "easy", tip: "Casual chats with coworkers build stronger work relationships." },
  { word: "ZOOM",   sentence: "We'll connect over ____ for our weekly team meeting.",        category: "Remote Work", hintCategory: "Work Style",      difficulty: "easy", tip: "Always test your camera and mic 5 minutes before any video call." },
  { word: "CODE",   sentence: "Developers write ____ to build software applications.",       category: "Tech",        hintCategory: "Technology",      difficulty: "easy", tip: "Learning to code opens doors in nearly every industry today." },

  // ========== MEDIUM ==========
  { word: "RESUME",   sentence: "Please send your updated ____ before the interview.",                category: "HR",          hintCategory: "Human Resources", difficulty: "medium", tip: "Keep your resume to one page if you have under 10 years experience." },
  { word: "SALARY",   sentence: "We can discuss your expected ____ during the next call.",            category: "Finance",     hintCategory: "Finance",         difficulty: "medium", tip: "Research market rates on Glassdoor before negotiating salary." },
  { word: "OFFER",    sentence: "I received a job ____ from my top choice company.",                  category: "HR",          hintCategory: "Human Resources", difficulty: "medium", tip: "Never accept a job offer on the spot — always sleep on it." },
  { word: "BUDGET",   sentence: "The marketing ____ for next quarter has been approved.",             category: "Finance",     hintCategory: "Finance",         difficulty: "medium", tip: "Set aside 10% of any budget for unexpected expenses." },
  { word: "CLIENT",   sentence: "We just signed a major ____ in the healthcare industry.",            category: "Marketing",   hintCategory: "Marketing",       difficulty: "medium", tip: "Keeping a client costs 5x less than finding a new one." },
  { word: "REPORT",   sentence: "The quarterly sales ____ shows strong growth this year.",            category: "Finance",     hintCategory: "Finance",         difficulty: "medium", tip: "Start every report with the key insight, not the methodology." },
  { word: "BONUS",    sentence: "All employees received a year-end ____ for hitting targets.",        category: "Finance",     hintCategory: "Finance",         difficulty: "medium", tip: "Bonuses typically range from 5-15% of your base salary." },
  { word: "REMOTE",   sentence: "She works ____ from her home office three days a week.",             category: "Remote Work", hintCategory: "Work Style",      difficulty: "medium", tip: "Remote workers report 22% higher job satisfaction overall." },
  { word: "LAPTOP",   sentence: "The company gives every new hire a brand new ____.",                 category: "Tech",        hintCategory: "Technology",      difficulty: "medium", tip: "Invest in a good laptop stand to prevent neck and back pain." },
  { word: "MEETING",  sentence: "The team ____ has been moved to 3 PM this afternoon.",               category: "Remote Work", hintCategory: "Work Style",      difficulty: "medium", tip: "Most meetings could be an email — always question the necessity." },
  { word: "MANAGER",  sentence: "My new ____ is supportive and gives great feedback.",                category: "HR",          hintCategory: "Human Resources", difficulty: "medium", tip: "People don't leave companies — they leave bad managers." },
  { word: "PROJECT",  sentence: "Our biggest ____ this year involves three different teams.",         category: "HR",          hintCategory: "Human Resources", difficulty: "medium", tip: "Break large projects into 2-week sprints for steady progress." },
  { word: "CAREER",   sentence: "She built a successful ____ in digital marketing over ten years.",   category: "HR",          hintCategory: "Human Resources", difficulty: "medium", tip: "Your career is a marathon, not a sprint — pace yourself well." },
  { word: "BRAND",    sentence: "A strong ____ helps a company stand out from competitors.",          category: "Marketing",   hintCategory: "Marketing",       difficulty: "medium", tip: "Consistent branding can increase company revenue by 23%." },
  { word: "SALES",    sentence: "Our ____ team exceeded their quota for the third month in a row.",   category: "Marketing",   hintCategory: "Marketing",       difficulty: "medium", tip: "The best salespeople listen 70% of the time and talk 30%." },
  { word: "PROFIT",   sentence: "The company reported record ____ for the fourth quarter.",           category: "Finance",     hintCategory: "Finance",         difficulty: "medium", tip: "Revenue is vanity, profit is sanity — watch your margins closely." },
  { word: "STARTUP",  sentence: "He joined a ____ in the AI industry last summer.",                   category: "Tech",        hintCategory: "Technology",      difficulty: "medium", tip: "Early startup employees often receive equity that can pay off big." },
  { word: "MENTOR",   sentence: "Finding a great ____ can speed up your career growth.",              category: "HR",          hintCategory: "Human Resources", difficulty: "medium", tip: "Mentees are 5x more likely to get promoted than non-mentees." },
  { word: "BENEFITS", sentence: "The company offers amazing health ____ to all employees.",           category: "HR",          hintCategory: "Human Resources", difficulty: "medium", tip: "Benefits can add 30-40% extra value to your base compensation." },

  // ========== HARD ==========
  { word: "INTERVIEW",  sentence: "My job ____ is scheduled for ten in the morning tomorrow.",          category: "HR",          hintCategory: "Human Resources", difficulty: "hard", tip: "Prepare three STAR-method stories for behavioral interviews." },
  { word: "PROMOTION",  sentence: "She earned a ____ to senior manager after two great years.",        category: "HR",          hintCategory: "Human Resources", difficulty: "hard", tip: "Document your wins monthly to build your case for promotion." },
  { word: "DEADLINE",   sentence: "The project ____ has been pushed back by one week.",                category: "HR",          hintCategory: "Human Resources", difficulty: "hard", tip: "Communicate early when a deadline might slip — never on the day." },
  { word: "FREELANCE",  sentence: "He left his job to ____ and work with multiple clients.",           category: "Remote Work", hintCategory: "Work Style",      difficulty: "hard", tip: "Save 30% of freelance income for taxes and slow months." },
  { word: "PORTFOLIO",  sentence: "Every designer should keep an updated ____ of their best work.",    category: "Marketing",   hintCategory: "Marketing",       difficulty: "hard", tip: "Show your 3-5 best projects, not every single thing you've made." },
  { word: "STRATEGY",   sentence: "We need a new marketing ____ for the upcoming product launch.",     category: "Marketing",   hintCategory: "Marketing",       difficulty: "hard", tip: "A great strategy says no to good ideas to focus on the great ones." },
  { word: "NETWORK",    sentence: "Building a strong professional ____ opens doors throughout your career.", category: "HR",      hintCategory: "Human Resources", difficulty: "hard", tip: "85% of jobs are filled through networking, not job boards." },
  { word: "FEEDBACK",   sentence: "Good managers give honest ____ in regular one-on-one meetings.",    category: "HR",          hintCategory: "Human Resources", difficulty: "hard", tip: "Ask for feedback monthly — don't wait for the annual review." },
  { word: "COLLEAGUE",  sentence: "My ____ in the next cubicle helped me debug the issue.",            category: "HR",          hintCategory: "Human Resources", difficulty: "hard", tip: "A friendly colleague today could be your boss or hire tomorrow." },
  { word: "ONBOARDING", sentence: "The first two weeks of ____ cover company culture and tools.",      category: "HR",          hintCategory: "Human Resources", difficulty: "hard", tip: "Great onboarding raises new-hire retention by 82%." },
  { word: "NEGOTIATE",  sentence: "Don't be afraid to ____ your salary before signing the offer.",     category: "Finance",     hintCategory: "Finance",         difficulty: "hard", tip: "The first number put on the table anchors the whole negotiation." },
  { word: "RECRUITER",  sentence: "A ____ from a top firm reached out about a senior role.",           category: "HR",          hintCategory: "Human Resources", difficulty: "hard", tip: "Build a relationship with recruiters even when you're not job hunting." },
  { word: "INTERNSHIP", sentence: "Her summer ____ turned into a full-time offer after graduation.",   category: "HR",          hintCategory: "Human Resources", difficulty: "hard", tip: "Treat every internship like a 12-week interview — because it is." },
  { word: "LEADERSHIP", sentence: "Strong ____ skills are essential for moving into management.",      category: "HR",          hintCategory: "Human Resources", difficulty: "hard", tip: "Leadership is influence — you don't need a title to lead." },
  { word: "WORKFLOW",   sentence: "We streamlined our team ____ to ship features twice as fast.",      category: "Tech",        hintCategory: "Technology",      difficulty: "hard", tip: "Map your workflow before automating it — bad processes scale badly." },
  { word: "TRAINING",   sentence: "All new engineers complete a six-week ____ program.",               category: "HR",          hintCategory: "Human Resources", difficulty: "hard", tip: "Companies that invest in training see 24% higher profit margins." },
  { word: "CONTRACT",   sentence: "Read every line of the ____ before signing on the dotted line.",    category: "Finance",     hintCategory: "Finance",         difficulty: "hard", tip: "Watch out for non-compete clauses that can limit your next move." },
  { word: "REFERENCE",  sentence: "List three people who can act as a professional ____ for you.",     category: "HR",          hintCategory: "Human Resources", difficulty: "hard", tip: "Always ask before listing someone as a reference — courtesy matters." },
  { word: "LINKEDIN",   sentence: "Update your ____ profile before starting your next job search.",    category: "Marketing",   hintCategory: "Marketing",       difficulty: "hard", tip: "Profiles with photos get 21x more views and 36x more messages." },
  { word: "BURNOUT",    sentence: "Take a real vacation each year to avoid career ____.",              category: "HR",          hintCategory: "Human Resources", difficulty: "hard", tip: "Burnout is now a recognized occupational phenomenon by the WHO." }
];
